#!/usr/bin/ruby

current_dir = File.expand_path(File.dirname(__FILE__))
files_dir = File.join(current_dir, "files")
 
files = Dir[File.join(files_dir, "*")] + Dir[File.join(files_dir, ".[^\.]*")]
files.each do |file|
  command = "ln -sfF #{file} $HOME/."
  puts command
  `#{command}`
end
